export const stationOptions = [
{label: 'Vælg station', value: 'Vælg station'},
{label: 'København H', value: 'København H'},
{label: 'Fredericia', value: 'Fredericia'},
{label: 'Københavns lufthavn Kastrup', value: 'Københavns lufthavn Kastrup'},
{label: 'Aarhus H', value: 'Aarhus H'},
{label: 'Esbjerg', value: 'Esbjerg'},
{label: 'Frederikshavn', value: 'Frederikshavn'},
{label: 'Herning', value: 'Herning'},
{label: 'Odense', value: 'Odense'},
{label: 'Padborg', value: 'Padborg'},
{label: 'Struer', value: 'Struer'},
{label: 'Vejle', value: 'Vejle'},
{label: 'Aalborg', value: 'Aalborg'},
{label: 'Kolding', value: 'Kolding'},
{label: 'Helgoland', value: 'Helgoland'},
{label: 'Helsingør', value: 'Helsingør'},
{label: 'Kalundborg', value: 'Kalundborg'},
{label: 'Nykøbing F', value: 'Nykøbing F'},
{label: 'Næstved', value: 'Næstved'},
{label: 'Ringsted', value: 'Ringsted'},
{label: 'Roskilde', value: 'Roskilde'},
{label: 'Køge', value: 'Køge'},
{label: 'Hillerød', value: 'Hillerød'},
{label: 'Østerport', value: 'Østerport'},
]