export const straekningOptions = [
{label: 'Vælg strækning', value: 'Vælg strækning'},
{label: 'B-1 København H - Fredericia', value: 'B-1 København H - Fredericia'},
{label: 'B-1.a København H - Taulov', value: 'B-1.a København H - Taulov'},
{label: 'B-1.b København H - Fredericia/Taulov', value: 'B-1.b København H - Fredericia/Taulov'},
{label: 'B-1.c København H - Roskilde', value: 'B-1.c København H - Roskilde'},
{label: 'B-1.d Roskilde - Ringsted', value: 'B-1.d Roskilde - Ringsted'},
{label: 'B-1.e Ringsted - Odense', value: 'B-1.e Ringsted - Odense'},
{label: 'B-1.f Odense - Snoghøj', value: 'B-1.f Odense - Snoghøj'},
{label: 'B-1.g Snoghøj - Fredericia', value: 'B-1.g Snoghøj - Fredericia'},
{label: 'B-1.h Snoghøj - Taulov', value: 'B-1.h Snoghøj - Taulov'},
{label: 'B-2 Ringsted - Rødby Færge', value: 'B-2 Ringsted - Rødby Færge'},
{label: 'B-2.a Ringsted - Næstved', value: 'B-2.a Ringsted - Næstved'},
{label: 'B-2.b Næstved - Nykøbing F.', value: 'B-2.b Næstved - Nykøbing F.'},
{label: 'B-2.c Nykøbing F. - Rødby Færge', value: 'B-2.c Nykøbing F. - Rødby Færge'},
{label: 'B-4 Roskilde - Næstved', value: 'B-4 Roskilde - Næstved'},
{label: 'B-4.a Roskilde - Køge [ERTMS]', value: 'B-4.a Roskilde - Køge [ERTMS]'},
{label: 'B-4.b Køge - Næstved', value: 'B-4.b Køge - Næstved'},
{label: 'B-5 Roskilde - Kalundborg', value: 'B-5 Roskilde - Kalundborg'},
{label: 'B-5.a Roskilde - Holbæk', value: 'B-5.a Roskilde - Holbæk'},
{label: 'B-5.b Holbæk - Kalundborg', value: 'B-5.b Holbæk - Kalundborg'},
{label: 'B-6 København H - Ringsted', value: 'B-6 København H - Ringsted'},
{label: 'B-6.a København H - Vigerslev', value: 'B-6.a København H - Vigerslev'},
{label: 'B-6.b Vigerslev - Ringsted', value: 'B-6.b Vigerslev - Ringsted'},
{label: 'B-7 Lersøen - Østerport', value: 'B-7 Lersøen - Østerport'},
{label: 'B-810 København H - Høje Taastrup', value: 'B-810 København H - Høje Taastrup'},
{label: 'B-820.a København H - Svanemøllen', value: 'B-820.a København H - Svanemøllen'},
{label: 'B-820.b Svanemøllen - Hillerød [CBTC]', value: 'B-820.b Svanemøllen - Hillerød [CBTC]'},
{label: 'B-830 Valby - Frederikssund', value: 'B-830 Valby - Frederikssund'},
{label: 'B-840 Svanemøllen - Farum', value: 'B-840 Svanemøllen - Farum'},
{label: 'B-850 København H - Køge', value: 'B-850 København H - Køge'},
{label: 'B-860 Hellerup - Klampenborg [CBTC]', value: 'B-860 Hellerup - Klampenborg [CBTC]'},
{label: 'B-880 Vigerslev - (Hellerup)', value: 'B-880 Vigerslev - (Hellerup)'},
{label: 'B-880 (Hellerup) - Lersøen [CBTC]', value: 'B-880 (Hellerup) - Lersøen [CBTC]'},
{label: 'B-10 København H - Helsingør', value: 'B-10 København H - Helsingør'},
{label: 'B-10.a København H - Østerport', value: 'B-10.a København H - Østerport'},
{label: 'B-10.b Østerport - Helgoland', value: 'B-10.b Østerport - Helgoland'},
{label: 'B-10.c Helgoland - Nivå', value: 'B-10.c Helgoland - Nivå'},
{label: 'B-10.d Nivå - Snekkersten', value: 'B-10.d Nivå - Snekkersten'},
{label: 'B-10.e Snekkersten - Helsingør', value: 'B-10.e Snekkersten - Helsingør'},
{label: 'B-11 København H - Peberholm', value: 'B-11 København H - Peberholm'},
{label: 'B-11.a København H - Kalvebod', value: 'B-11.a København H - Kalvebod'},
{label: 'B-11.b Hvidovre Fjern - Kalvebod', value: 'B-11.b Hvidovre Fjern - Kalvebod'},
{label: 'B-11.c Kalvebod - Københavns Lufthavn Kastrup', value: 'B-11.c Kalvebod - Københavns Lufthavn Kastrup'},
{label: 'B-11.d Københavns Lufthavn Kastrup - Peberholm', value: 'B-11.d Københavns Lufthavn Kastrup - Peberholm'},
{label: 'B-21 Odense - Svendborg', value: 'B-21 Odense - Svendborg'},
{label: 'B-23 Fredericia - Aarhus H', value: 'B-23 Fredericia - Aarhus H'},
{label: 'B-23.a Fredericia - Vejle', value: 'B-23.a Fredericia - Vejle'},
{label: 'B-23.b Vejle - Skanderborg', value: 'B-23.b Vejle - Skanderborg'},
{label: 'B-23.c Skanderborg - Aarhus H', value: 'B-23.c Skanderborg - Aarhus H'},
{label: 'B-24 Aarhus H - Aalborg', value: 'B-24 Aarhus H - Aalborg'},
{label: 'B-24.a Aarhus H - Langå', value: 'B-24.a Aarhus H - Langå'},
{label: 'B-24.b Langå - Randers', value: 'B-24.b Langå - Randers'},
{label: 'B-24.c Randers - Aalborg', value: 'B-24.c Randers - Aalborg'},
{label: 'B-25 Aalborg - Frederikshavn', value: 'B-25 Aalborg - Frederikshavn'},
{label: 'B-25.a Aalborg - Sulsted', value: 'B-25.a Aalborg - Sulsted'},
{label: 'B-25.b Sulsted - Frederikshavn [ERTMS]', value: 'B-25.b Sulsted - Frederikshavn [ERTMS]'},
{label: 'B-26 Fredericia - Padborg', value: 'B-26 Fredericia - Padborg'},
{label: 'B-26.a Fredericia - Taulov', value: 'B-26.a Fredericia - Taulov'},
{label: 'B-26.b Taulov - Kolding', value: 'B-26.b Taulov - Kolding'},
{label: 'B-26.c Kolding - Lunderskov', value: 'B-26.c Kolding - Lunderskov'},
{label: 'B-26.d Lunderskov - Tinglev', value: 'B-26.d Lunderskov - Tinglev'},
{label: 'B-26.e Tinglev - Padborg', value: 'B-26.e Tinglev - Padborg'},
{label: 'B-28 Sønderborg- Tinglev', value: 'B-28 Sønderborg- Tinglev'},
{label: 'B-29 Lunderskov - Esbjerg', value: 'B-29 Lunderskov - Esbjerg'},
{label: 'B-29.a Lunderskov - Bramming', value: 'B-29.a Lunderskov - Bramming'},
{label: 'B-29.b Bramming - Esbjerg', value: 'B-29.b Bramming - Esbjerg'},
{label: 'B-30 Bramming - Tønder grænse', value: 'B-30 Bramming - Tønder grænse'},
{label: 'B-30.a Bramming - Tønder', value: 'B-30.a Bramming - Tønder'},
{label: 'B-30.b Tønder - Tønder grænse', value: 'B-30.b Tønder - Tønder grænse'},
{label: 'B-31 Esbjerg - Struer', value: 'B-31 Esbjerg - Struer'},
{label: 'B-31.a Esbjerg - Varde', value: 'B-31.a Esbjerg - Varde'},
{label: 'B-31.b Varde - Skjern', value: 'B-31.b Varde - Skjern'},
{label: 'B-31.c Skjern - Vemb', value: 'B-31.c Skjern - Vemb'},
{label: 'B-31.d Vemb - Holstebro', value: 'B-31.d Vemb - Holstebro'},
{label: 'B-31.e Holstebro - Struer', value: 'B-31.e Holstebro - Struer'},
{label: 'B-32 Langå - Struer', value: 'B-32 Langå - Struer'},
{label: 'B-32.a Langå - Viborg', value: 'B-32.a Langå - Viborg'},
{label: 'B-32.b Viborg - Struer', value: 'B-32.b Viborg - Struer'},
{label: 'B-33 Holstebro - Vejle', value: 'B-33 Holstebro - Vejle'},
{label: 'B-33.a Holstebro - Herning', value: 'B-33.a Holstebro - Herning'},
{label: 'B-33.b Herning - Vejle', value: 'B-33.b Herning - Vejle'},
{label: 'B-34 Struer - Thisted', value: 'B-34 Struer - Thisted'},
{label: 'B-35 Skanderborg - Skjern', value: 'B-35 Skanderborg - Skjern'},
{label: 'B-35.a Skanderborg - Silkeborg', value: 'B-35.a Skanderborg - Silkeborg'},
{label: 'B-35.b Silkeborg - Herning', value: 'B-35.b Silkeborg - Herning'},
{label: 'B-35.c Herning - Skjern ', value: 'B-35.c Herning - Skjern '},
{label: 'Aarhus Letbane (AAL)', value: 'Aarhus Letbane (AAL)'},
{label: 'Lokaltog, Region Hovedstaden', value: 'Lokaltog, Region Hovedstaden'},
{label: 'Lokaltog, Region Syd', value: 'Lokaltog, Region Syd'},
{label: 'Midtjyske Jernbaner', value: 'Midtjyske Jernbaner'},
{label: 'Nordjyske Jernbaner', value: 'Nordjyske Jernbaner'}
]